<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>JuiceLog</RootNamespace>
        <UserSecretsId>JuiceLog-a84cedcd-2bc3-409a-83cc-61bded25f283</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FFMpegCore" Version="5.2.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.6" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Quartz" Version="3.14.0" />
      <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.14.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2"/>
      <PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0" />
    </ItemGroup>
    
</Project>